# Dependencies
#markdown: redcarpet
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: 'Wandevs'
tagline: 'Wanchain Developers Portal'
description: 'We build on Wanchain'

url: https://wandevs.net

# Custom vars
version: 0.1.0

github:
 repo: https://github.com/wandevs
